- README.md
- android/app/src/alpha/res/values/strings.xml
- android/app/src/beta/res/values/strings.xml
- android/app/src/debug/res/values/strings.xml
- android/app/src/main/AndroidManifest.xml
- android/app/src/prod/res/values/strings.xml
- ios/Configuration/alpha.xcconfig
- ios/Configuration/beta.xcconfig
- ios/Configuration/dev.xcconfig
- ios/Configuration/prod.xcconfig
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
> #1 Added support for flavored names. 

- README.md
> #3 Updated the readme to specify the flavor you are running on

- lib/di/injector.dart
- lib/di/injector.g.dart
- lib/util/interceptor/network_log_interceptor.dart
- pubspec.yaml
#6 should be fixed with this pr
> #6 place the interceptor in a seperate file

- assets/locale/en.json
- assets/locale/nl.json
- lib/screen/home/home_screen.dart
- lib/util/locale/localization.dart
- lib/viewmodel/home/home_viewmodel.dart
> #9 Updated the flow to get the right content in your list

- README.md
- pubspec.lock
- pubspec.yaml
Updated readme to point to new github repo for niddler-ui
> Update niddler_dart to last version that fixes web support

- .gitignore
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/com/icapps/flutter_template/MainActivity.kt
- android/app/src/main/kotlin/com/icapps/flutter_template/bridge/LoggerPlugin.kt
- android/app/src/main/res/values/styles.xml
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- ios/Runner/Packages/LoggerPlugin.swift
- lib/screen/home/home_screen.dart
- lib/screen/license/license_screen.dart
- pubspec.lock
- pubspec.yaml
- test/viewmodel/error_navigator_test.dart
> #74 fixed android v2 embedding + flutter version 1.22

- fastlane/Fastfile
- ios/Runner.xcodeproj/project.pbxproj
- lib/database/flutter_template_database.g.dart
- lib/di/injector.g.dart
- lib/webservice/todo/todo_webservice.g.dart
- pubspec.lock
- pubspec.yaml
- test/di/test_injector.g.dart
> Updated packages & fixed fastlane to use fvm instead

- fastlane/Fastfile
> #78: Added the repo update command to the fastfile

- lib/navigator/main_navigator.dart
- lib/widget/general/text_scale_factor.dart
> #69: Disabled the textScaleFactor

- fastlane/Fastfile
Fixed #66
Fixed #64
Fixed #57
Fixed #56
Fixed #55
> Fastlane changes

- tool/dart_tool/install_fvm.dart
> #102: Fixed strict mode

- .gitignore
> #109: Added gemfile.lock to the gitignore

- lib/repository/secure_storage/secure_storage.dart
- lib/repository/secure_storage/secure_storing.dart
- lib/repository/shared_prefs/shared_prefs_storage.dart
- lib/repository/shared_prefs/shared_prefs_storing.dart
- test/repository/secure_storage/secure_storage_test.dart
- test/repository/shared_prefs/shared_prefs_storage_test.dart
> #104: Added contains key to the secure storing & shared prefs

- .fvm/fvm_config.json
> Correct flutter versions

- lib/di/injector.dart
- lib/di/injector.g.dart
- lib/util/cache/cache_controller.dart
- lib/util/cache/cache_controlling.dart
- lib/util/env/flavor_config.dart
- lib/widget/general/styled/flutter_template_network_image.dart
- lib/widget/general/text_scale_factor.dart
- pubspec.lock
- pubspec.yaml
> #123: Added the better network image widget

- lib/webservice/todo/todo_dummy_service.dart
> Fixed error for dummy service

- lib/architecture.dart
- lib/widget/general/styled/flutter_template_button.dart
- lib/widget/general/styled/flutter_template_progress_indicator.dart
- lib/widget/provider/data_provider_widget.dart
- lib/widget/provider/provider_widget.dart
> Fixed #162 & use the provider widget & theme provider widget

- tool/dart_tool/rename_project.dart
- tool/dart_tool/strip_boilerplate_project.dart
- tool/install_fvm.sh
> Update scripting with comments

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
> Updated the gradle version

- lib/main_common.dart
> Ensure we always print zoned errors

- .fvm/fvm_config.json
- lib/styles/theme_data.dart
- pubspec.lock
> #238: Updated to flutter 2.10.4

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
> #235: fixed the ndk missmatch error

- fastlane/analysis_options_check_compilation.yaml
> Update analysis options

- lib/util/interceptor/network_log_interceptor.dart
- test/util/interceptor/network_log_interceptor_test.dart
> 184 Don't log not modified as error

- test/screen/permission/analytics_permission_screen_test.dart
- tool/dart_tool/strip_boilerplate_project.dart
Updated remove boilerplate script with tabs and navigator lines to delete
> Fix pipeline fails

- lib/navigator/main_navigator.dart
- lib/screen/debug/debug_platform_selector_screen.dart
- lib/screen/debug/debug_screen.dart
- lib/screen/home/home_screen.dart
- lib/screen/license/license_screen.dart
- lib/screen/login/login_screen.dart
- lib/screen/permission/analytics_permission_screen.dart
- lib/screen/splash/splash_screen.dart
- lib/screen/theme_mode/theme_mode_selector.dart
- lib/screen/todo/todo_add/todo_add_screen.dart
> #290: removed routenames

- .github/workflows/rename_project.yml
- .github/workflows/strip_boilerplate_project.yaml
- .github/workflows/strip_boilerplate_project_remove_tests.yaml
> #310: fix ci job names

- build.yaml
- lib/database/flutter_template_database.dart
- lib/database/flutter_template_database.g.dart
- lib/di/injectable.dart
> #314: optimized build.yaml

- lib/navigator/main_navigator.dart
- lib/styles/theme_durations.dart
- lib/util/snackbar/error_util.dart
- lib/util/snackbar/snackbar_util.dart
- lib/viewmodel/login/login_viewmodel.dart
- lib/webservice/todo/todo_dummy_service.dart
- lib/widget/animation/animated_color_filter.dart
- lib/widget/general/action/text_action_item.dart
- lib/widget/general/bottom_navigation/bottom_navigation_item.dart
- lib/widget/general/styled/flutter_template_button.dart
- pubspec.lock
- pubspec.yaml
- test/styles/theme_durations_test.dart
- test/util/test_util.mocks.dart
- test/viewmodel/debug/debug_platform_selector_viewmodel_test.mocks.dart
- test/viewmodel/debug/debug_viewmodel_test.mocks.dart
- test/viewmodel/license/license_viewmodel_test.mocks.dart
- test/viewmodel/login/login_viewmodel_test.dart
- test/viewmodel/login/login_viewmodel_test.mocks.dart
- test/viewmodel/theme_selector/theme_selector_viewmodel_test.mocks.dart
- test/viewmodel/todo/todo_add/todo_add_viewmodel_test.mocks.dart
- test/viewmodel/todo/todo_list/todo_list_viewmodel_test.mocks.dart
> #313: removed getx and added flushbar

- fastlane/Fastfile
- tool/dart_tool/firebase/android_firebase_uploader.dart
- tool/dart_tool/firebase/firebase_uploader.dart
- tool/dart_tool/firebase/ios_firebase_uploader.dart
- tool/dart_tool/rename_project.dart
> #295 firebase deobfuscation

- .vscode/settings.json
> Excluded .fvm files from vscode search/watching

- lib/model/exceptions/bad_request_error.dart
- lib/model/exceptions/forbidden_error.dart
- lib/model/exceptions/general_error.dart
- lib/model/exceptions/general_network_error.dart
- lib/model/exceptions/internal_server_error.dart
- lib/model/exceptions/no_internet_error.dart
- lib/model/exceptions/un_authorized_error.dart
- lib/util/interceptor/network_error_interceptor.dart
- lib/util/interceptor/network_log_interceptor.dart
- test/repository/refresh/refresh_repository_test.dart
- test/util/interceptor/network_error_interceptor_test.dart
- test/viewmodel/login/login_viewmodel_test.dart
- test/viewmodel/todo/todo_list/todo_list_viewmodel_test.dart
> #322 fix nullability in errors

- .github/workflows/analyzer.yml
- .github/workflows/rename_project.yml
- .github/workflows/strip_boilerplate_project.yaml
- .github/workflows/strip_boilerplate_project_remove_tests.yaml
- tool/rename_project.sh
- tool/strip_boilerplate_project_project.sh
> Added fvm for all scripts

- .github/workflows/analyzer.yml
- .github/workflows/rename_project.yml
- .github/workflows/strip_boilerplate_project.yaml
- .github/workflows/strip_boilerplate_project_remove_tests.yaml
- .github/workflows/test.yml
> FT-346: Updated checkout action
